### ISSUE TITLE
GNUMakefile changes for successful make

### ISSUE THREAD

**Issue by sg-hk** [nmeum/insomnia#2]
There are two issues in the current GNUMakefile which prevent the project from being built (on my machine at least). They're easy to fix:

1. bin/\*.in files not being substituted to bin/\* 
**Error:**
chmod +w bin/insomnia
chmod: cannot access 'bin/insomnia': No such file or directory
make: *** [GNUmakefile:20: bin/insomnia] Error 1
**Fix:**
Move the "chmod +w $@" line after the sed substitution

2. warning on deprecated flag
**Error:**
cc -o lib/insomnia-color lib/insomnia-color.c -Werror -Os -std=c99 -D_POSIX_C_SOURCE=200809L -D_BSD_SOURCE -Wpedantic -Wall -Wextra 
In file included from /usr/include/err.h:22,
                 from lib/insomnia-color.c:1:
/usr/include/features.h:197:3: error: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
  197 | # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
      |   ^~~~~~~
cc1: all warnings being treated as errors
make: *** [GNUmakefile:27: lib/insomnia-color] Error 1
**Fix:**
Change the relevant CFLAGS line to -D_DEFAULT_SOURCE

**Comment by nmeum** [comment]
Should be fixed now, went for a slightly different approach though. However, thanks a lot for your detailed and informative report!

Let me know if you find anything else :)

**Comment by sg-hk** [comment]
And thank you for all the great repos you've shared with the world!
